web/docker_django/applications/backend/urls.py
from django.conf.urls import url
from django.urls import include

from applications.backend import views

app_name = 'backend'

urlpatterns = [
    url(r'^$', views.index_backend, name='index_backend'),
    url(r'^not_processed_eservice$', views.not_processed_eservice, name='not_processed_eservice'),
    url(r'^eservices$', views.eservices, name='eservices'),
    url(r'^eservices/rating/', views.eservices_bystar, name='bystar_rating'),
    url(r'^my_eservices', views.my_eservices, name='my_eservices'),
    url(r'^eservice/create/$', views.backend_eservice_create, name='backend_eservice_create'),
    url(r'^eservice/create/+(?P<eservice_type>[0-9a-zA-Z_]+)', views.create_eservice_backend,
        name='create_eservice_backend'),
    url(r'^eservice/delete/+(?P<eservice_id>[0-9_]+)', views.delete_eservice_backend,
        name='delete_eservice_backend'),
    url(r'^eservice/update/+(?P<eservice_id>[0-9_]+)/(?P<step>[0-9]+)', views.update_eservice_backend,
        name='update_eservice'),
    url(r'^', include('support.urls')),

    url(r'^workflow/+(?P<eservice_id>[0-9]+)/approve/', views.approve, name='approve'),
    url(r'^workflow/+(?P<eservice_id>[0-9]+)/reject/', views.reject, name='reject'),
    url(r'^workflow/+(?P<eservice_id>[0-9]+)/to_approve/', views.to_approve, name='approve'),
    url(r'^workflow/+(?P<eservice_id>[0-9]+)/to_edit/', views.to_edit, name='to_edit'),
    url(r'^eservice/+(?P<eservice_id>[0-9]+)', views.eservice_page, name='eservice_page'),

]

web/docker_django/applications/eservice/urls.py
from django.conf.urls import url, include

from eservice import views

urlpatterns = [
    url(r'^create/$', views.eservice_create, name='eservice_create'),
    url(r'^my_eservices/$', views.my_eservices, name='my_eservices'),
    url(r'^create/+(?P<eservice_type>[0-9a-zA-Z_]+)', views.create_eservice,
        name='create_eservice'),
    url(r'^create/$', views.eservice_create, name='eservice_create'),
    url(r'^estimation_service/+(?P<eservice_id>[0-9a-zA-Z_]+)$', views.estimation_service, name='estimation_service'),

    url(r'^another_sign/+(?P<encoded>.*)/', views.another_sign, name='another_sign'),
    url(r'^eservice_signature/+(?P<eservice_id>[0-9a-zA-Z_]+)$', views.eservice_signature, name='eservice_signature'),
    url(r'^(?P<eservice_id>[0-9]+)', views.eservice_page_front, name='eservice_page'),

]

web/docker_django/eservices/nadra/urls.py
from django.conf.urls import url
from django.urls import path

from eservices.nadra import views
from nadra.frontend.views import *

urlpatterns = [
    url(r'^city_load/$', views.city_load, name='city_load'),
    path('areas', views.areas_load, name='areas_load'),
    url(r'^send_to_another/+(?P<eservice_id>[0-9a-zA-Z_]+)$', send_to_another, name='send_to_another'),
    url(r'^step-2/+(?P<eservice_id>[0-9a-zA-Z_]+)$', step_2, name='step_2'),
    url(r'^step-3/+(?P<eservice_id>[0-9a-zA-Z_]+)$', step_3, name='step_3'),
    url(r'^step-4/+(?P<eservice_id>[0-9a-zA-Z_]+)$', step_4, name='step_4'),
    url(r'^step-5/+(?P<eservice_id>[0-9a-zA-Z_]+)$', step_5, name='step_5'),
    url(r'^step-6/+(?P<eservice_id>[0-9a-zA-Z_]+)$', step_6, name='step_6'),

]

web/docker_django/system/urls.py
from decorator_include import decorator_include
from django.conf.urls import url, include, re_path
from django.contrib import admin
from django.contrib.auth.decorators import permission_required, login_required
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path
from django.http.response import HttpResponse
from django.views.generic.base import TemplateView
from django.views.decorators.csrf import csrf_exempt

from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns

from system import views

# urlpatterns = i18n_patterns(
from system.decorators import group_required

urlpatterns = [
    path('_admin/', admin.site.urls),
    url(r'^$', views.index, name='index'),
    url(r"^robots\.txt$", csrf_exempt(views.robots), name="robots_file"),
    url(r'^auth/', include('authorization.urls'), name='auth'),  # авторизація
    url(r'accounts/login/$', views.return_reg_template, name='login'),
    url(r'^sign/', include('signature.urls'), name='sign'),
    url(r'^eservice/', include('eservice.urls')),
    url(r'^eservice0100043/', include('eservice0100043.urls')),
    url(r'^eservice/nadra/', include('eservices.nadra.urls')),
    url(r'^client_api/', include('client_api.urls')),

    path('backend/', decorator_include(group_required(['Оператори', 'Керівники']), 'backend.urls')),

    url(r'^backend/reports/', include('reports.urls')),
    url(r'^users/', include('users.urls')),
    url(r'^', include('support.urls')),
    url(r'^nested_admin/', include('nested_admin.urls')),
    # url(r'^report_builder/', include('report_builder.urls')),
    re_path(r'^elements/',  views.elements, name='elements'),
    re_path(r'^documentation/',  views.documentation, name='documentation'),
    re_path(r'^trembita/', include('modules.trembita.urls')),
    re_path(r'^sev/', include('modules.sev_ovv.urls')),
    re_path(r'infinitive/$', views.infinitive, name='infinitive'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web/docker_django/applications/backend/models.py
from django.db import models

# Create your models here.

web/docker_django/applications/eservice/models.py
import os
from datetime import datetime

from django.core.exceptions import ValidationError
from django.db import models
from django.conf import settings
from django.db.models import QuerySet
from django_extensions.db.fields.json import JSONField
from django.contrib.auth import get_user_model
from mptt.fields import TreeForeignKey
from mptt.models import MPTTModel

User = get_user_model()


def validate_capitalized(value):
    if value[0] != value[0].capitalize():
        raise ValidationError('Введіть будь ласка назву з великої літери: %(value)s',
                              code='invalid',
                              params={'value': value})


def file_extension(value):
    import os
    ext = os.path.splitext(value.name)[1]
    valid_extensions = ['.pdf', '.doc', '.docx', '.odt', '.rtf', '.jpg', '.jpeg', '.png', '.tif', '.tiff', '.xls',
                        '.xlsx']
    if not ext.lower() in valid_extensions:
        raise ValidationError('Недоступне розширення файлу')


class HideOldVersion(models.Manager):
    def get_queryset(self):
        return super(HideOldVersion, self).get_queryset().filter(is_archival=False)


class EService(models.Model):
    internal_id = models.CharField(max_length=128, unique=True, null=False, blank=False,
                                   verbose_name='Індекс реєстрації послуги')
    created_at = models.DateTimeField(default=datetime.now, verbose_name="Створено")
    title = models.CharField(max_length=512, blank=False, null=False, verbose_name='Короткий опис',
                             validators=[validate_capitalized])
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, null=True, verbose_name="Автор картки",
                                   on_delete=models.CASCADE)
    created_by_ip = models.CharField(default='127.0.0.1', max_length=15, verbose_name='IP адреса автора картки')
    deadline = models.DateField(null=True, verbose_name='Кінечний строк')
    close_at = models.DateTimeField(null=True, verbose_name="Послугу завершенно")
    type = models.ForeignKey('EServiceType', default=1, verbose_name='Тип послуги', on_delete=models.SET_DEFAULT)
    version = models.IntegerField(null=False, default="1", verbose_name='Версія послуги')
    period_extended = models.DateTimeField(null=True, blank=True, verbose_name="Дата продовження послуги")
    resolutioner = models.ForeignKey(User, null=True, verbose_name="Накладає резолюцію", on_delete=models.SET_NULL,
                                     related_name="resolutioner")
    status = models.ForeignKey('EServiceMeta', null=True, verbose_name="Стан послуги", default=6,
                               on_delete=models.SET_DEFAULT)
    resolutioner_viewed = models.BooleanField(default=False, verbose_name="Переглянуто резолюцілнером")
    edit_comment = models.CharField(max_length=1024, null=True, verbose_name="Коментар відправившого на доопрацювання")
    # TODO: реалізувати безпечне видалення
    is_deleted = models.CharField(max_length=10, null=True, verbose_name='Видалено?', default=False)

    # Показуємо тільки
    # objects = HideOldVersion()
    # all = models.Manager()

    def __str__(self):
        return self.title

    class Meta:
        db_table = 'eservice'
        verbose_name = 'Послуги'
        verbose_name_plural = 'Послуги'
        unique_together = ["internal_id", "id"]
        select_on_save = True


# types of document
class EServiceType(models.Model):
    title = models.CharField(max_length=128)
    category = models.CharField(max_length=128, default='Вхідна кореспонденція')
    controller = models.CharField(max_length=128, default='dev')
    model = models.CharField(max_length=128, default='EService')

    class Meta:
        db_table = 'eservice_type'
        verbose_name = 'Тип послуги'
        verbose_name_plural = 'Типи послуги'

    def __str__(self):
        return self.title


class EServiceStatus(models.Model):
    '''
    Статуси для типів послуги
    '''
    title = models.CharField(max_length=160, default='Чернетка')
    slug = models.CharField(max_length=60, default='draft')
    color = models.CharField(max_length=60, default='text-default')

    class Meta:
        db_table = 'eservice_status'
        verbose_name = 'Статус послуги'
        verbose_name_plural = 'Статуси послуги'
        unique_together = ('title', 'slug',)

    def __str__(self):
        return self.title


# Файли тримаємо у папках з іменами ID відповідних послуг
def user_directory_path(instance, filename):
    ext = filename.split('.')[-1]
    filename = "{}__{}__{:%d-%m-%Y}__ID-{}.{}".format(
        instance.eservice.type.title,
        instance.eservice.internal_id.replace("/","."),
        instance.eservice.created_at,
        instance.eservice.id, ext)
    return 'eservice_files/{0}/{1}'.format(instance.eservice.id, filename)


class EServiceFile(models.Model):
    """
    Збереження файлів для послуги.
    """
    created_at = models.DateTimeField(default=datetime.now)
    eservice = models.ForeignKey(EService, verbose_name="Послугу", null=True, on_delete=models.CASCADE)
    author = models.ForeignKey(User, null=True, on_delete=models.CASCADE)
    file = models.FileField(upload_to=user_directory_path, blank=False, null=False, validators=[file_extension])
    filename = models.CharField(max_length=128, null=False, default="Custom name")
    mime = models.CharField(max_length=150, default="image/jpeg", verbose_name="Тип файлу")
    size = models.IntegerField(null=True, verbose_name="Розмір файлу")

    class Meta:
        db_table = 'eservice_file'
        verbose_name = 'Файл'
        verbose_name_plural = 'Файли'


class EServiceSign(models.Model):
    """

    """
    created_at = models.DateTimeField(default=datetime.now)
    eservice = models.ForeignKey(EService, verbose_name="Послугу", null=True, on_delete=models.CASCADE)
    user = models.ForeignKey(User, null=True, on_delete=models.CASCADE)

    class Meta:
        db_table = 'eservice_sign'
        verbose_name = 'Підпис файлу'
        verbose_name_plural = 'Підпис файлу'
        unique_together = (('eservice', 'user'),)


# Логування усіх дій по послуги
class EServiceLog(models.Model):
    activity = models.CharField(max_length=512, blank=True)
    eservice = models.ForeignKey(EService, null=False, blank=False, on_delete=models.CASCADE)
    created_at = models.DateTimeField(default=datetime.now)
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, null=True, on_delete=models.CASCADE)

    class Meta:
        db_table = 'eservice_log'
        verbose_name = 'Лог подій по послуги'
        verbose_name_plural = 'Логі подій по послуги'


class EServiceStar(models.Model):
    eservice = models.ForeignKey(EService, null=True, blank=True, on_delete=models.CASCADE)
    created_at = models.DateTimeField(default=datetime.now, null=True, blank=True)
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, default=1, null=True, on_delete=models.CASCADE)
    quality = models.FloatField(null=True, blank=True, default=None)
    easy_ordering = models.FloatField(null=True, blank=True, default=None)
    term_service = models.FloatField(null=True, blank=True, default=None)
    average_value = models.FloatField(null=True, blank=True, default=None)
    comment = models.TextField(default='', blank=True, null=True)

    class Meta:
        db_table = 'eservice_star'
        verbose_name = 'Оцінюваня надання послуги'
        verbose_name_plural = 'Оцінюваня надання послуги'


class EServiceMeta(MPTTModel):
    eservice_type = models.ForeignKey(EServiceType, null=True, blank=True, on_delete=models.SET_NULL)
    category_index = models.CharField(max_length=10, null=False, verbose_name="Індекс категорії")
    title = models.CharField(max_length=1024, null=False, verbose_name="Назва")
    parent = TreeForeignKey('self', null=True, blank=True, related_name='children', db_index=True,
                            verbose_name="Батьківська категорія", on_delete=models.SET_NULL)
    is_active = models.BooleanField(default=True, verbose_name="Активна?")
    is_category = models.BooleanField(default=False, verbose_name="Категорія?")

    created_at = models.DateTimeField(default=datetime.now)
    attr = JSONField(blank=True, null=True, verbose_name='Додаткова інформація')

    objects = QuerySet.as_manager()

    class MPTTMeta:
        order_insertion_by = ['category_index']

    class Meta:
        db_table = 'eservice_meta'
        verbose_name = 'Мета-інформація'
        verbose_name_plural = 'Мета-інформація'

    def __str__(self):
        return "{} ({})".format(self.title, self.category_index)


# =============== Допоміжні функції по роботі з моделями ==============#

class Log:
    '''
    Логування основних дій
    '''

    def __init__(self, **kwargs):
        self.eservice_id = kwargs['eservice_id']
        self.action = kwargs['action']
        self.user = kwargs['user']
        self.time = datetime.now()

    def write(self):
        try:
            EServiceLog.objects.create(
                eservice=EService.objects.get(pk=self.eservice_id),
                activity=self.action,
                created_by=self.user,
                created_at=self.time
            ).save()
        except Exception as e:
            return "Помилка запису логу події: {}".format(e)


# Погодження послуги
class EServiceOnApproving(models.Model):
    eservice = models.ForeignKey(EService, on_delete=models.CASCADE)
    assign_to = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(default=datetime.now)
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, null=True, related_name="created_approver_item_by",
                                   on_delete=models.CASCADE)
    created_by_ip = models.CharField(default='127.0.0.1', max_length=15)
    done = models.IntegerField(default=0)
    done_at = models.DateTimeField(null=True)
    viewed = models.BooleanField(default=False)
    viewed_at = models.DateTimeField(null=True)

web/docker_django/applications/eservice/forms.py
from django import forms
from eservice.models import EServiceStar
from django.forms import Form


class DocumentStarForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(DocumentStarForm, self).__init__(*args, **kwargs)
        self.fields['comment'].label = "Ваш коментар по наданню послуги"
        self.fields['comment'].attrs = {'class': 'textarea_md'}

    quality = forms.FloatField(label="Якість наданої послуги", required=False, max_value=10,
                               min_value=0, widget=forms.NumberInput(attrs={'id': 'quality'}))
    easy_ordering = forms.FloatField(label="Легкість замовлення послуги", required=False, max_value=10,
                                     min_value=0, widget=forms.NumberInput(attrs={'id': 'easy_ordering'}))
    term_service = forms.FloatField(label="Строк надання послуги", required=False, max_value=10,
                                    min_value=0, widget=forms.NumberInput(attrs={'id': 'term_service'}))
    comment = forms.TextInput(attrs={'class': 'textarea_md'})

    class Meta:
        model = EServiceStar
        fields = [
            'quality',
            'easy_ordering',
            'term_service',
            'comment',
        ]

web/docker_django/eservices/eservice0100043/backend/forms.py
from django import forms
from eservice0100043.models import EService0100043
from eservices.eservice0100043.forms import EServiceForm0100043


class EServiceBackendForm0100043(EServiceForm0100043):
    def __init__(self, *args, **kwargs):
        super(EServiceBackendForm0100043, self).__init__(*args, **kwargs)

    class Meta:
        model = EService0100043
        fields = [
            "title",
            "comment",
            "deadline",
            "type_license",
            "payment",
            "region",
            "city",

        ]
        widgets = {
            "title": forms.TextInput(attrs={
                "class": "form-control",
                "placeholder": "Короткий опис не більше 512 символів"
            }),
        }

web/docker_django/applications/backend/templates/backend/eservices.html
{% extends 'backend/base_with_filter.html' %}
{% load staticfiles %}
{% block breadcrumb%}
    <div class="gpdk-pageheader">
        <ol class="breadcrumb slim-breadcrumb">
            <li class="breadcrumb-item"><a href="/backend/">Головна</a></li>
            <li class="breadcrumb-item active" aria-current="page">послуги організації</li>
        </ol>
        <h6 class="gpdk-pagetitle">Послуги організації</h6>
    </div>
{% endblock %}

{% block content %}
<div class="container section-wrapper">
    <div class="row">
        <div class="col-md-12 col-lg-12">
            <div class="table-responsive">
                {% if e_services %}
                    <table class="table mg-b-0">
                      <thead>
                        <tr>
                          <th>Назва</th>
                          <th>Статус</th>
                          <th>Дата створення</th>
                        </tr>
                      </thead>
                      <tbody>
                        {% for item in e_services %}
                          <tr>
                            <th>
                              <a href="/backend/eservice/{{ item.id }}">
                                {{ item.title }}
                              </a>
                            </th>
                              <td> <span class="label  {{ item.status.attr.slug }}">{{ item.status.title }}</span></td>
                            <td>{{ item.created_at }}</td>
                          </tr>
                        {%endfor%}
                      </tbody>
                    </table>
                {%else%}
                    * Немає послуг організації
                {%endif%}
              </div>
        </div>
    </div>
</div>
{% endblock %}

web/docker_django/applications/backend/templates/backend/eservices_by_stars.html
{% extends 'backend/base_with_filter.html' %}
{% load staticfiles %}
{% block breadcrumb%}
    <div class="gpdk-pageheader">
        <ol class="breadcrumb slim-breadcrumb">
            <li class="breadcrumb-item"><a href="/backend/">Головна</a></li>
            <li class="breadcrumb-item active" aria-current="page">послуги організації</li>
        </ol>
        <h6 class="gpdk-pagetitle">Послуги з оцінкою {{ desciption }}</h6>
    </div>
{% endblock %}

{% block content %}
<div class="container section-wrapper">
    <div class="row">
        <div class="col-md-12 col-lg-12">
            <div class="table-responsive">
                {% if eservices %}
                    <table class="table mg-b-0">
                      <thead>
                        <tr>
                          <th>Назва</th>
                          <th>Статус</th>
                          <th>Дата створення</th>
                          <th>Оцінка</th>
                        </tr>
                      </thead>
                      <tbody>
                        {% for item in eservices %}
                          <tr>
                            <th>
                              <a href="/backend/eservice/{{ item.id }}">
                                {{ item.title }}
                              </a>
                            </th>
                              <td> <span class="label color-esdf {{ item.status.attr.slug }}">{{ item.status.title }}</span></td>
                            <td>{{ item.created_at }}</td>
                            <td>{{ item.eservicestar_set.first.average_value }}</td>
                          </tr>
                        {%endfor%}
                      </tbody>
                    </table>
                {%else%}
                    * Немає послуг з даним типом оцінки
                {%endif%}
              </div>
        </div>
    </div>
</div>
{% endblock %}

web/docker_django/applications/backend/templates/backend/my_eservices.html
{% extends 'backend/base_with_filter.html' %}
{% load staticfiles %}
{% block breadcrumb%}
    <div class="gpdk-pageheader">
        <ol class="breadcrumb slim-breadcrumb">
            <li class="breadcrumb-item"><a href="/backend/">Головна</a></li>
            <li class="breadcrumb-item active" aria-current="page">Мої послуги</li>
        </ol>
        <h6 class="gpdk-pagetitle">Мої послуги</h6>
    </div>
{% endblock %}

{% block content %}
<div class="container section-wrapper">
    <div class="row">
        <div class="col-md-12 col-lg-12">
            <div class="table-responsive">
                {% if my_e_services %}
                    <table class="table mg-b-0">
                      <thead>
                        <tr>
                          <th>Назва</th>
                          <th>Статус</th>
                          <th>Дата створення</th>
                        </tr>
                      </thead>
                      <tbody>
                        {% for item in my_e_services %}
                          <tr>
                            <th>
                              <a href="/backend/eservice/{{ item.id }}">
                                {{ item.title }}
                              </a>
                            </th>
                              <td> <span class="label  {{ item.status.attr.slug }}"> {{ item.status.title }}</span></td>
                            <td>{{ item.created_at }}</td>
                          </tr>
                        {%endfor%}
                      </tbody>
                    </table>
                {%else%}
                    * У Вас немає послуг
                {%endif%}
              </div>
        </div>
    </div>
</div>
{% endblock %}

web/docker_django/applications/backend/templates/backend/stars_module.html
{% load staticfiles %}
{% load stars_filter %}
<div class="table-responsive mt-4 bg-white">
            <table class="table table-bordered tx-center">
              <thead class="thead-colored">
                <tr>
                  <th class="wd-75p bg-esdf text-white">Оцінка</th>
                  <th class="wd-2p bg-esdf text-white">Кількість</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <th scope="row">Відмінно (8-10) <i class="fa fa-star"></i></th>
                  <td><a href="eservices/rating/?stars=maximum">{{ star|stars_filter:'maximum' }}</a></td>
                </tr>
                <tr>
                  <th scope="row">Добре (6-8)<i class="fa fa-star-half-full"></i></th>
                    <td><a href="eservices/rating/?stars=good">{{ star|stars_filter:'good' }}</a></td>
                </tr>
              <tr>
                  <th scope="row">Посередньо (4-6)<i class="fa fa-star-half-o"></i></th>
                  <td><a href="eservices/rating/?stars=average">{{ star|stars_filter:'average' }}</a></td>
                </tr>
              <tr>
                  <th scope="row">Погано (2-4)<i class="fa fa-star-half-o"></i></th>
                  <td><a href="eservices/rating/?stars=bad">{{ star|stars_filter:'bad' }}</a></td>
                </tr>
              <tr>
                  <th scope="row">Дуже погано (0-2)<i class="fa fa-star-o"></i></th>
                  <td><a href="eservices/rating/?stars=worst">{{ star|stars_filter:'worst' }}</a></td>
                </tr>
              </tbody>
            </table>
          </div>